### ISSUE TITLE
Merge strings for translation

### ISSUE THREAD

**Issue by vladutilie** [shamim2883/front-end-pm#18]
Hello,

I want to translate the plugin in [Romanian language](https://translate.wordpress.org/projects/wp-plugins/front-end-pm/stable/ro/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and I encountered a small issue in this file: /includes/class-fep-directory.php. Because of variable number of users, the string "successfully blocked" cannot be correctly translated in Romanian (there are different forms of singular and plural nouns in Romanian).

Regarding this point, could you merge, please, these lines into a single one?
**1. class-fep-directory.php, lines 199 - 201**
```php
$message = sprintf(_n('%s user', '%s users', $count, 'front-end-pm'), number_format_i18n($count) );
$message .= ' ';
$message .= __('successfully blocked.', 'front-end-pm');
```
**Proposed solution:**
```php
$message = sprintf( _n( '%s user successfully blocked.', '%s users successfully blocked.', $count, 'front-end-pm' ), number_format_i18n( $count ) );
```

**2. class-fep-directory.php, lines 206 - 208**
```php
$message = sprintf(_n('%s user', '%s users', $count, 'front-end-pm'), number_format_i18n($count) );
$message .= ' ';
$message .= __('successfully unblocked.', 'front-end-pm');
```
**Proposed solution:**
```php
$message = sprintf( _n( '%s user successfully unblocked.', '%s users successfully unblocked.', $count, 'front-end-pm' ), number_format_i18n( $count ) );
```

**3. The same for includes/class-fep-message.php, lines 369 - 382**
```php
$message = sprintf(_n('%s message', '%s messages', $count, 'front-end-pm'), number_format_i18n($count) );
$message .= ' ';
 
if( 'delete' == $action ){
   $message .= __('successfully deleted.', 'front-end-pm');
} elseif( 'mark-as-read' == $action ){
    $message .= __('successfully marked as read.', 'front-end-pm');
} elseif( 'mark-as-unread' == $action ){
   $message .= __('successfully marked as unread.', 'front-end-pm');
} elseif( 'archive' == $action ){
   $message .= __('successfully archived.', 'front-end-pm');
} elseif( 'restore' == $action ){
   $message .= __('successfully restored.', 'front-end-pm');
}
```
**Proposed solution:**
```php
if( 'delete' == $action ){
    $message = sprintf(_n('%s message successfully deleted.', '%s messages successfully deleted.', $count, 'front-end-pm'), number_format_i18n($count) );
} elseif( 'mark-as-read' == $action ){
    $message = sprintf(_n('%s message successfully marked as read.', '%s messages successfully marked as read.', $count, 'front-end-pm'), number_format_i18n($count) );
} elseif( 'mark-as-unread' == $action ){
    $message = sprintf(_n('%s message successfully marked as unread.', '%s messages successfully marked as unread.', $count, 'front-end-pm'), number_format_i18n($count) );
} elseif( 'archive' == $action ){
    $message = sprintf(_n('%s message successfully archived.', '%s messages successfully archived.', $count, 'front-end-pm'), number_format_i18n($count) );
} elseif( 'restore' == $action ){
    $message = sprintf(_n('%s message successfully restored.', '%s messages successfully restored.', $count, 'front-end-pm'), number_format_i18n($count) );
}
```

Best regards,
Vlad

P.S: If you want, I would like to be a [Project Translation Editor (PTE)](https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#requesting-new-translation-editors) for Romanian language of this plugin. Thanks! 👍

**Comment by shamim2883** [comment]
Thank you. Can you please check if you can find any more string like this which cannot be translated in your language?
If you are comfortable you can fork or edit file and make pull request.
I will make a PTE request for you. Please give me your wordpress username

**Comment by vladutilie** [comment]
Sure, for ease of flow I will make a pull request, thank you 👍 
My WordPress username is **[vladwtz](https://profiles.wordpress.org/vladwtz)**.
