### ISSUE TITLE
fep_shortcode_message_to doesn't work

### ISSUE THREAD

**Issue by sebastienserre** [shamim2883/front-end-pm#70]
Hello,
I'm using your WP Plugin in a project and the shortcode [fep_shortcode_message_to to="{current-post-author}" subject="{current-post-title}"] doesn't work.

It makes a link sending to the Home Page...

**Comment by sebastienserre** [comment]
sorry, it was a setting mistake

**Comment by shamim2883** [comment]
For support please use support forums.
For PRO version: https://www.shamimsplugins.com/support/forum/front-end-pm-pro/
For Free version: https://wordpress.org/support/plugin/front-end-pm/
